src/Entity/Film.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use Doctrine\Common\Collections\Collection;
use Doctrine\Common\Collections\ArrayCollection;

// To use UniqueEntity in Annotations
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;

/**
 * @ORM\Entity(repositoryClass="App\Repository\FilmRepository")
 * @UniqueEntity("titel", message="Elke film moet een unieke titel hebben")
 */
class Film
{
    /**
     * Generates the magic method!!
     * for labels  
     */
    public function __toString()
    {
        // to show the titel of the Exemplaar in the select
        return $this->titel;
        // return $this->lidwoord;
        // return $this->imdb_movie_id;
    }

    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $titel;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $lidwoord;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $imdb_movie_id;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Exemplaar", mappedBy="idFilm", orphanRemoval=true)
     */
    private $exemplaren;

    public function __construct()
    {
        $this->exemplaren = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitel(): ?string
    {
        return $this->titel;
    }

    public function setTitel(string $titel): self
    {
        $this->titel = $titel;

        return $this;
    }

    public function getLidwoord(): ?string
    {
        return $this->lidwoord;
    }

    public function setLidwoord(?string $lidwoord): self
    {
        $this->lidwoord = $lidwoord;

        return $this;
    }

    public function getImdbMovieId(): ?string
    {
        return $this->imdb_movie_id;
    }

    public function setImdbMovieId(?string $imdb_movie_id): self
    {
        $this->imdb_movie_id = $imdb_movie_id;

        return $this;
    }

    /**
     * @return Collection|Exemplaar[]
     */
    public function getExemplaren(): Collection
    {
        return $this->exemplaren;
    }

    public function addExemplaren(Exemplaar $exemplaren): self
    {
        if (!$this->exemplaren->contains($exemplaren)) {
            $this->exemplaren[] = $exemplaren;
            $exemplaren->setIdFilm($this);
        }

        return $this;
    }

    public function removeExemplaren(Exemplaar $exemplaren): self
    {
        if ($this->exemplaren->contains($exemplaren)) {
            $this->exemplaren->removeElement($exemplaren);
            // set the owning side to null (unless already changed)
            if ($exemplaren->getIdFilm() === $this) {
                $exemplaren->setIdFilm(null);
            }
        }

        return $this;
    }
}

src/Form/FilmType.php
<?php

namespace App\Form;

use App\Entity\Film;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class FilmType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('titel')
            ->add('lidwoord')
            ->add('imdb_movie_id')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Film::class,
        ]);
    }
}

src/Controller/FilmController.php
<?php

namespace App\Controller;

use App\Entity\Film;
use App\Form\FilmType;
use App\Entity\Exemplaar;
use App\Repository\FilmRepository;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

/**
 * @Route("/film")
 */
class FilmController extends AbstractController
{
    public function showFilms($films)
    {
        $filmsExemplaren = [];
        foreach ($films as $film) {
            $id = $film->getId();

            $exemplaren = $this->getDoctrine()
                ->getRepository(Exemplaar::class)
                ->findBy(
                    ['idFilm' => $id],
                    // Sorteer ze
                    array('nummer' => 'asc')
                );
            array_push($filmsExemplaren, [$film, $exemplaren]);
        }
        return $filmsExemplaren;
    }

    /**
     * @Route("/", name="film_index", methods={"GET"})
     */
    public function index(FilmRepository $filmRepository): Response
    {
        // $films = $filmRepository->findAllAsc();
        // $filmsExemplaren = self::showFilms($films);

        return $this->render('film/index.html.twig', [
            // 'filmsExemplaren' => $filmsExemplaren
            'filmsExemplaren' => self::showFilms($filmRepository->findAllAsc())
        ]);
    }

    /**
     * @Route("/new", name="film_new", methods={"GET","POST"})
     * @IsGranted("ROLE_ADMIN")
     */
    public function new(Request $request): Response
    {
        $film = new Film();
        $form = $this->createForm(FilmType::class, $film);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($film);
            $entityManager->flush();

            return $this->redirectToRoute('film_index');
        }

        return $this->render('film/new.html.twig', [
            'film' => $film,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="film_show", methods={"GET"})
     */
    public function show(Film $film): Response
    {
        // haal info op op basis van imdb_movie_id
        $url = 'http://www.omdbapi.com/?i=' . $film->getImdbMovieId() . '&apikey=' . $_ENV["OMDB_KEY"]; // path to your JSON file
        $data = file_get_contents($url); // put the contents of the file into a variable
        $json = json_decode($data, true); // decode the JSON feed     

        // Toont alle exemplaren van film
        $exemplaarRepository = $this->getDoctrine()->getRepository(Exemplaar::class);
        $exemplaar = $exemplaarRepository->findBy(
            ["idFilm" => $film->getId()]
        );

        return $this->render('film/show.html.twig', [
            'film' => $film,
            'json' => $json,
            'exemplaar' => $exemplaar

        ]);
    }

    /**
     * @Route("/{id}/edit", name="film_edit", methods={"GET","POST"})
     * @IsGranted("ROLE_ADMIN")
     */
    public function edit(Request $request, Film $film): Response
    {
        $form = $this->createForm(FilmType::class, $film);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('film_index', [
                'id' => $film->getId(),
            ]);
        }

        return $this->render('film/edit.html.twig', [
            'film' => $film,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="film_delete", methods={"DELETE"})
     * @IsGranted("ROLE_ADMIN")
     */
    public function delete(Request $request, Film $film): Response
    {
        if ($this->isCsrfTokenValid('delete' . $film->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($film);
            $entityManager->flush();
        }

        return $this->redirectToRoute('film_index');
    }
}

templates/film/_delete_form.html.twig
<form method="post" action="{{ path('film_delete', {'id': film.id}) }}" onsubmit="return confirm('Ben je zeker dat je dit item wilt verwijderen?');">
    <input name="_method" type="hidden" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ film.id) }}">
    <button class="ui button">Verwijder</button>
</form>

templates/film/_form.html.twig
{{ form_start(form,  {'attr': {'class': 'form ui error'} }) }}

{% if not form.vars.valid %}
    {% set error = true %}
    <div class="ui message error">
        {{ form_errors(form) }}
        {{ form_errors(form.titel) }}
        {{ form_errors(form.lidwoord) }}
        {{ form_errors(form.imdb_movie_id) }}
    </div>
{% endif %}

<div
    class="three fields">
    {# enkel titel kan een error geven #}
    <div class="field {% if error is defined  %} error {% endif %} ">
        {{ form_label(form.titel)}}
        {{ form_widget(form.titel, {'attr': {'placeholder': 'Godfather: Part II'}}) }}
    </div>
    <div class="field ">
        {{ form_label(form.lidwoord)}}
        {{ form_widget(form.lidwoord, {'attr': {'placeholder': 'The'}}) }}
    </div>
    <div class="field ">
        {{ form_label(form.imdb_movie_id)}}
        {{ form_widget(form.imdb_movie_id, {'attr': {'placeholder': 'tt0071562'}}) }}
    </div>
</div>

<button class="ui button primary left floated">
    {{ button_label|default('Save') }}
</button>


{{ form_end(form) }}

templates/film/delete.html.twig
{% extends 'base.html.twig' %}

{% block title %}Delete Film
{% endblock %}

{% block body %}
    <h1 class="title">Delete Film</h1>

    {{ include('film/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('film_index') }}">Terug naar filmoverzicht</a>

    {{ include('film/_delete_form.html.twig') }}
{% endblock %}

templates/film/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Film
{% endblock %}

{% block body %}
    <h1 class="title">Film aanpassen</h1>

    {{ include('film/_form.html.twig', {'button_label': 'Update'}) }}
    {{ include('film/_delete_form.html.twig') }}

    <a href="{{ path('film_index') }}">Terug naar filmoverzicht</a>
{% endblock %}

templates/film/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}
    Film index
{% endblock %}

{% block body %}
    <h1 class="ui dividing header">
        {% if query is defined %}
            Resultaten voor
            {{ query }}
        {% else %}
            Filmoverzicht
        {% endif %}
    </h1>

    <table class="ui celled striped table">
        <thead>
            <tr>

                {# <th>Id</th> #}
                <th>Titel</th>
                <th>Nummer(s)</th>
                <th>Aanwezig</th>
                <th>IMDb</th>
                {% if is_granted('ROLE_ADMIN') %}
                    <th class="collapsing two">Acties</th>
                {% endif %}
            </tr>
        </thead>
        <tbody>
            {% for value in filmsExemplaren %}
                <tr>
                    {# <td>{{ film.id }}</td> #}
                    <td>
                        <a href="{{ path('film_show', {'id': value.0.id}) }}">
                            {{ value.0.titel }}
                            {% if value.0.lidwoord is not empty  %}
                                ,
                                {{ value.0.lidwoord }}
                            {% endif %}
                        </a>
                    </td>
                    <td>
                        {% set totaal = 0 %}
                        {% if value.1 is not empty %}
                            {% for item in value.1 %}
                                <a href="{{ path('exemplaar_show', {'id': item.id}) }}">
                                    {% if item.aanwezig > 0 %}
                                        <strong>{{ item.nummer }}</strong>
                                        {% set totaal = totaal + 1 %}
                                    {% else %}
                                        {{ item.nummer }}
                                    {% endif %}
                                </a>
                            {% endfor %}
                        {% endif %}
                    </td>
                    <td>
                        {{ totaal }}
                    </td>
                    <td>
                        <a href="https://www.imdb.com/title/{{ value.0.imdbMovieId }}" rel="noopener noreferrer" target="_blank">imdb</a>
                    </td>
                    {% if is_granted('ROLE_ADMIN') %}
                        <td>
                            <a href="{{ path('film_edit', {'id': value.0.id}) }}">Bewerk</a>
                        </td>
                    {% endif %}
                </tr>
            {% else %}
                <tr>
                    <td colspan="5">Geen films gevonden</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>

    {% if is_granted('ROLE_ADMIN') %}
        <a href="{{ path('film_new') }}">Nieuwe film</a>
    {% endif %}
{% endblock %}

templates/film/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Film
{% endblock %}

{% block body %}
    <h1 class="title">Nieuwe film toevoegen</h1>

    {{ include('film/_form.html.twig') }}
    <a class="clear" href="{{ path('film_index') }}">Terug naar filmoverzicht</a>
{% endblock %}

templates/film/show.html.twig
{% extends 'base.html.twig' %}


{% block title %}
    {{film.titel}}
{% endblock %}

{% block body %}

    <div class="ui items">
        <div class="item">
            <div class="ui medium image rounded">
                {% if json.Poster is defined %}
                    <img src="{{json.Poster}}">
                {% else %}
                    <img src="https://via.placeholder.com/300x445">
                {% endif %}

            </div>
            <div class="middle content">
                <h1>
                    {{film.titel}}
                    {% if film.lidwoord is not empty  %}
                        ,
                        {{ film.lidwoord }}
                    {% endif %}
                    {% if json.Year is defined %}
                        <small>
                            ({{ json.Year}})
                        </small>
                    {% endif %}
                </h1>
                <div class="meta">
                    <span>Omschrijving</span>
                </div>
                <div class="description">
                    <p>
                        {% if json.Plot is defined %}
                            {{ json.Plot}}
                        {% else %}
                            Geen beschrijving
                        {% endif %}
                    </p>
                    <br>
                </div>
                <div class="meta">
                    <span>Onderscheiding(en)</span>
                </div>
                <div class="description">
                    <p>
                        {% if json.Awards is defined and json.Awards != 'N/A' %}
                            {{ json.Awards}}
                        {% else %}
                            Onbekend
                        {% endif %}
                    </p>
                </div>

                <div class="extra">
                    {% if json.Genre is defined %}
                        Genre:
                        {{ json.Genre}}
                    {% endif %}
                    {% if json.Genre is defined %}
                        |
                        <i class="hourglass half icon"></i>
                        {{ json.Runtime}}
                    {% endif %}
                    {% if json.imdbRating is defined %}
                        |
                        <i class="star icon"></i>
                        {{ json.imdbRating}}
                    {% endif %}
                </div>
                <div></br>
                {% if is_granted('ROLE_ADMIN') %}
                    <a class="left floated" href="{{ path('film_edit', {'id': film.id}) }}">
                        <button class="ui button">Bewerk</button>
                    </a>
                    {{ include('film/_delete_form.html.twig') }}
                {% endif %}
                <a href="{{ path('film_index') }}">Terug naar filmoverzicht</a>
            </div>
        </div>
    </div>
    {# {% if not exemplaar.vars.valid %} #}

    {% set titel = "Exemplaren van " ~ film.titel  %}
    {% include "exemplaar/table.html.twig" with {exemplaars :exemplaar, titel: titel } %}

</div>{% endblock %}